AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

SERVICE_CONTAINER_CLS: src.container.ServiceContainer

ENTRYPOINT_BLACKLIST:
  ${BLACKLIST_ENTRYPOINTS}
